import { fallbackMemorySynthesis } from './npcmemory.mjs?v=visitor1';
import { commitNpcConversationNarrative } from './npcnarrativecontinuity.mjs?v=visitor1';
import { beginPlayerConversation, recordPlayerConversationOutcome } from './npcrumor.mjs';
import { rememberSocialMemory } from './npcsocialmemory.mjs';
import { registerLivingWorldEntity } from './livingworldstate.mjs';

export const VISITOR_CONVERSATION_VERSION = 1;
const MAX_DISTANCE = 9;
const MAX_CONTEXT_BYTES = 11_000;
const MAX_TRANSCRIPT_MESSAGES = 18;

/** Host-owned boundary for conversations generated by a visitor's local model. */
export class HostVisitorConversationService {
  constructor({ population, authority, save = null } = {}) {
    this.population = population;
    this.authority = authority;
    this.save = typeof save === 'function' ? save : () => population?.livingWorldStore?.save?.(population.worldState);
    this.sessions = new Map();
  }

  open(playerId, { npcId, homeOrigin = null } = {}) {
    if (this.sessions.size >= 64) {
      const oldest = [...this.sessions.entries()].sort((a, b) => a[1].startedAt - b[1].startedAt)[0];
      if (oldest) this.sessions.delete(oldest[0]);
    }
    const visitor = this.authority?.visitors?.get?.(playerId);
    const actor = this.population?.actorById?.(npcId);
    if (!visitor || !actor) throw new Error('That resident is not available.');
    if (this.population.isTalkingTo?.(npcId)) throw new Error('That resident is already occupied.');
    const position = actor.avatar?.root?.position || actor.remotePose;
    if (!position || Math.hypot(position.x - visitor.pose.x, position.z - visitor.pose.z) > MAX_DISTANCE) {
      throw new Error('Move closer to the resident.');
    }
    const origin = normalizeOrigin(homeOrigin || visitor.homeOrigin);
    const memory = this.population.memoryStore.load(npcId, playerId);
    const context = this.population.contextForActor(actor, {
      playerId,
      homeOrigin: origin,
      encounterCount: memory.meetingCount,
      playerPosition: visitor.pose,
    });
    const conversation = beginPlayerConversation(this.population.worldState, npcId, {
      playerId, nowHour: this.population.worldState.clock.worldHours,
    });
    const conversationId = `visitor:${conversation.id}`;
    if (this.population.reserveRemoteDialogue
      && !this.population.reserveRemoteDialogue(npcId, conversationId)) {
      throw new Error('That resident is already occupied.');
    }
    const originLabel = origin?.stationName ? `traveller from ${origin.stationName}` : 'traveller';
    registerLivingWorldEntity(this.population.worldState, {
      id: playerId, kind: 'player', name: originLabel, role: 'traveller',
      homeOrigin: origin,
    });
    this.sessions.set(conversationId, {
      playerId, npcId, context, conversation, transcript: [], committed: false, startedAt: Date.now(),
    });
    return { version: VISITOR_CONVERSATION_VERSION, conversationId, context: compactContext(context) };
  }

  checkpoint(playerId, { conversationId, transcript } = {}) {
    const session = this.requireSession(playerId, conversationId);
    session.transcript = validateTranscript(transcript, playerId, session.npcId);
    return { version: VISITOR_CONVERSATION_VERSION, acceptedMessages: session.transcript.length };
  }

  commit(playerId, { conversationId, transcript, synthesis } = {}) {
    const session = this.requireSession(playerId, conversationId);
    if (session.committed) return { version: VISITOR_CONVERSATION_VERSION, committed: true, duplicate: true };
    const accepted = Array.isArray(transcript) && transcript.length
      ? validateTranscript(transcript, playerId, session.npcId)
      : session.transcript;
    if (Array.isArray(transcript) && transcript.length && session.transcript.length
      && JSON.stringify(accepted) !== JSON.stringify(session.transcript)) {
      throw new Error('Conversation transcript did not match its last checkpoint.');
    }
    if (!accepted.length) throw new Error('An empty conversation cannot be committed.');

    const store = this.population.memoryStore;
    const previous = store.load(session.npcId, playerId);
    // The visitor's model output is a proposal. Durable personal memory is
    // rebuilt from the host-validated transcript, so a modified client cannot
    // insert facts that were never said. Narrative claims below pass their own
    // quote/index/subject validator before entering the graph.
    const memory = fallbackMemorySynthesis(previous, session.context, accepted);
    const saved = store.save(session.npcId, memory, playerId);
    recordPlayerConversationOutcome(this.population.worldState, session.conversation, {
      npcId: session.npcId,
      playerId,
      playerTurns: accepted.filter((message) => message.role === 'user').length,
      nowHour: this.population.worldState.clock.worldHours,
    });
    rememberVisit(this.population.worldState, session, saved);
    if (this.population.features?.npcNarrativeFactPropagationEnabled && session.context.homeCommunity) {
      commitNpcConversationNarrative({
        state: this.population.worldState,
        context: session.context,
        transcript: accepted,
        synthesis,
        memoryStore: store,
      });
    }
    session.committed = true;
    this.population.releaseRemoteDialogue?.(session.npcId, conversationId);
    this.save();
    return {
      version: VISITOR_CONVERSATION_VERSION,
      committed: true,
      meetingCount: saved.meetingCount,
      rememberedName: learnedName(saved),
    };
  }

  closePlayer(playerId) {
    for (const [id, session] of this.sessions) {
      if (session.playerId !== playerId) continue;
      if (!session.committed && session.transcript.length) {
        try { this.commit(playerId, { conversationId: id, synthesis: null }); } catch { /* release below */ }
      }
      this.population.releaseRemoteDialogue?.(session.npcId, id);
      this.sessions.delete(id);
    }
  }

  requireSession(playerId, conversationId) {
    const session = this.sessions.get(String(conversationId || ''));
    if (!session || session.playerId !== playerId) throw new Error('Conversation is no longer active.');
    return session;
  }
}

function rememberVisit(state, session, memory) {
  const name = learnedName(memory);
  const origin = session.context?.player?.originLabel || 'traveller';
  const subject = name ? `${name}, a ${origin}` : `a ${origin}`;
  const summary = `${subject} visited and spoke with ${session.context.npc.name}.`;
  const lineageId = `visitor-meeting:${session.conversation.id}`;
  rememberSocialMemory(state, session.npcId, {
    id: `memory:${session.npcId}:${lineageId}`,
    ownerId: session.npcId,
    subject: { kind: 'player', id: session.playerId },
    predicate: 'visitor.met',
    object: { text: summary },
    summary,
    source: { kind: 'player', id: session.playerId },
    sourceChain: [{ kind: 'player', id: session.playerId }],
    provenance: 'observed',
    originEventId: `event:${session.conversation.id}:player-conversation`,
    lineageId,
    confidence: 1,
    salience: 0.86,
    privacy: 'shared',
    hopCount: 0,
    createdAtHour: state.clock.worldHours,
    lastRecalledHour: state.clock.worldHours,
    expiresAtHour: null,
  }, { nowHour: state.clock.worldHours });
  state.revision += 1;
}

function learnedName(memory) {
  for (const fact of memory?.playerFacts || []) {
    const match = /traveller'?s name is\s+([^.!?]+)/i.exec(fact);
    if (match) return match[1].trim().slice(0, 120);
  }
  return null;
}

function normalizeOrigin(value) {
  if (!value?.stationId || !value?.stationName) return null;
  return {
    regionId: String(value.regionId || '').slice(0, 96),
    stationId: String(value.stationId).slice(0, 96),
    stationName: String(value.stationName).replace(/[\u0000-\u001f]/g, '').trim().slice(0, 64),
    settlementId: value.settlementId ? String(value.settlementId).slice(0, 120) : null,
  };
}

function validateTranscript(value, playerId, npcId) {
  if (!Array.isArray(value) || value.length > MAX_TRANSCRIPT_MESSAGES) throw new Error('Conversation transcript is invalid.');
  return value.map((message, index) => {
    const role = message?.role;
    const content = typeof message?.content === 'string'
      ? message.content.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/g, '').trim().slice(0, 500)
      : '';
    if (!['user', 'assistant'].includes(role) || !content) throw new Error('Conversation message is invalid.');
    if (role === 'user' && message.speakerId !== playerId) throw new Error('Visitor message identity is invalid.');
    if (role === 'assistant' && message.speakerId !== npcId) throw new Error('Resident message identity is invalid.');
    if (index && value[index - 1]?.role === role) throw new Error('Conversation roles must alternate.');
    return { role, content, speakerId: role === 'user' ? playerId : npcId, source: role === 'assistant' ? String(message.source || 'authored').slice(0, 24) : undefined };
  });
}

function compactContext(context) {
  const copy = JSON.parse(JSON.stringify(context));
  if (Array.isArray(copy.targets)) copy.targets = copy.targets.slice(0, 12);
  if (Array.isArray(copy.pointPlaces)) copy.pointPlaces = copy.pointPlaces.slice(0, 8);
  if (Array.isArray(copy.homeCommunity?.residents)) copy.homeCommunity.residents = copy.homeCommunity.residents.slice(0, 12);
  if (Array.isArray(copy.memory?.socialMemories)) copy.memory.socialMemories = copy.memory.socialMemories.slice(0, 8);
  if (JSON.stringify(copy).length > MAX_CONTEXT_BYTES) delete copy.pointPlaces;
  if (JSON.stringify(copy).length > MAX_CONTEXT_BYTES && copy.homeCommunity) copy.homeCommunity.residents = copy.homeCommunity.residents?.slice(0, 6) || [];
  if (JSON.stringify(copy).length > MAX_CONTEXT_BYTES) delete copy.homeCommunity;
  if (JSON.stringify(copy).length > MAX_CONTEXT_BYTES) throw new Error('Resident context is too large to send.');
  return copy;
}
